
version: '3.7'

services:
  express:
    network_mode: "host"
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 80:8081
    #environment:
      #ME_CONFIG_MONGODB_ADMINUSERNAME: root
      #ME_CONFIG_MONGODB_ADMINPASSWORD: example
